name: peptide
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - addict
  - ipykernel
  - matplotlib
  - nbdev<2
  # - numpy<1.22
  # - nvidia::cudatoolkit=11.3
  - pandas
  - pip
  - python=3.9
  - pytorch
  - pyyaml
  - scikit-learn
  # - scipy
  - seaborn
  # - threadpoolctl>3
  - tqdm
  - pip:
      - biopython
      - fair-esm==0.5.0
      - h5py
      - xgboost==1.6.1
