name: peptide
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - addict #?
  - fastcore[version='>=1.3.8']
  - fastprogress[version='>=0.2.4'] #?
  - h5py
  - matplotlib
  - nbdev
  - nvidia::cudatoolkit=11.3
  - pandas
  - pip
  - python=3.9
  - pytorch
  - pyyaml #?
  - requests #?
  - scikit-learn
  - seaborn
  - pip:
      - xgboost
