name: peptide
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - nbdev
  - pandas
  - addict
  - fastprogress[version='>=0.2.4']
  - pyyaml
  - matplotlib
  - scikit-learn
  - requests
  - fastcore[version='>=1.3.8']
  - pytorch
  - py-xgboost-cpu
