name: peptide
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - addict
  - ipykernel
  - matplotlib
  - nbdev<2
  - pandas
  - pip
  - python=3.9
  - pytorch
  - pyyaml
  - scikit-learn<1.1.2
  - seaborn
  - tqdm
  - pip:
      - biopython
      - fair-esm==0.5.0
      - h5py
      - xgboost==1.6.1
