name: peptide
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - addict
  - fastcore[version='>=1.3.8']
  - h5py
  - matplotlib
  - nbdev<2
  - nvidia::cudatoolkit=11.3
  - pandas
  - pip
  - python=3.9
  - pytorch
  - pyyaml
  - scikit-learn
  - seaborn
  - tqdm
  - pip:
      - biopython
      - fair-esm
      - xgboost
