# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_device": "00_basics.ipynb",
         "settings_template": "00_basics.ipynb",
         "read_settings": "00_basics.ipynb",
         "DEVICE": "00_basics.ipynb",
         "settings": "00_basics.ipynb",
         "DATA_STORE": "00_basics.ipynb",
         "LOG_STORE": "00_basics.ipynb",
         "MODEL_STORE": "00_basics.ipynb",
         "EXPERIMENT_STORE": "00_basics.ipynb",
         "PATH_AMP": "00_basics.ipynb",
         "PATH_ACP": "00_basics.ipynb",
         "PATH_DNA_BINDING": "00_basics.ipynb",
         "get_acp_data": "01_preprocessing_data.ipynb",
         "get_amp_data": "01_preprocessing_data.ipynb",
         "get_dna_bind_data": "01_preprocessing_data.ipynb",
         "get_all_data": "01_preprocessing_data.ipynb",
         "extract_features_labels": "01_preprocessing_data.ipynb",
         "one_hot_encode": "02_preprocessing_embedding.ipynb"}

modules = ["basics.py",
           "preprocessing/data.py",
           "preprocessing/embedding.py"]

doc_url = "https://vin00d.github.io/peptide/"

git_url = "https://github.com/vin00d/peptide/tree/master/"

def custom_doc_links(name): return None
