# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_device": "00_basics.ipynb",
         "settings_template": "00_basics.ipynb",
         "read_settings": "00_basics.ipynb",
         "DEVICE": "00_basics.ipynb",
         "settings": "00_basics.ipynb",
         "DATA_STORE": "00_basics.ipynb",
         "LOG_STORE": "00_basics.ipynb",
         "MODEL_STORE": "00_basics.ipynb",
         "EXPERIMENT_STORE": "00_basics.ipynb",
         "PATH_AMP": "00_basics.ipynb",
         "PATH_ACP": "00_basics.ipynb",
         "PATH_DNA_BINDING": "00_basics.ipynb",
         "ProteinDataset": "01_data.ipynb",
         "ACPDataset": "01_data.ipynb",
         "AMPDataset": "01_data.ipynb",
         "DNABindDataset": "01_data.ipynb",
         "visualize_2pcs": "02_core.ipynb",
         "visualize_3pcs": "02_core.ipynb",
         "train_predict": "02_core.ipynb",
         "Learner": "02_core.ipynb",
         "create_param_grid": "03_onehot.ipynb",
         "run_gridsearch": "03_onehot.ipynb"}

modules = ["basics.py",
           "data.py",
           "core.py",
           "onehot.py",
           "lstm.py",
           "transformer.py"]

doc_url = "https://vin00d.github.io/peptide/"

git_url = "https://github.com/vin00d/peptide/tree/master/"

def custom_doc_links(name): return None
