# AUTOGENERATED! DO NOT EDIT! File to edit: 00_basics.ipynb (unless otherwise specified).

__all__ = ['get_device', 'settings_template', 'read_settings', 'DEVICE', 'settings', 'DATA_STORE', 'LOG_STORE',
           'MODEL_STORE', 'EXPERIMENT_STORE', 'PATH_AMP', 'PATH_ACP', 'PATH_DNA_BINDING']

# Cell

from addict import Dict
from collections import OrderedDict
from pathlib import Path

import yaml
import torch

# Cell

def get_device():
    '''Checks to see if GPU is available and sets device to GPU or CPU'''
    use_cuda = torch.cuda.is_available()
    if use_cuda:
        assert torch.backends.cudnn.enabled == True
        torch.backends.cudnn.benchmark = True #Enable cuDNN auto-tuner - perf benefit for convs
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")
    return device

# Cell

def settings_template():
    '''Create initial settings for library'''
    template = {
        'STORES' :
        {
            'DATA_STORE'       : f'{Path.home()}/.peptide/datasets',
            'LOG_STORE'        : f'{Path.home()}/.peptide/logs',
            'MODEL_STORE'      : f'{Path.home()}/.peptide/models',
            'EXPERIMENT_STORE' : f'{Path.home()}/.peptide/experiments'
        }
    }

    return template

# Cell

def read_settings():
    '''Read settings file at "~/.peptide/settings.yaml", if doesnt exist, create it from template'''
    settings_dir = f'{Path.home()}/.peptide'
    settings_file = Path(f'{settings_dir}/settings.yaml')

    if not settings_file.exists():
        print('No settings file found, so creating from template ..')
        settings = Dict(settings_template())
        Path.mkdir(Path(settings_dir), exist_ok=True)
        with open(settings_file, 'w') as s:
            yaml.dump(settings.to_dict(), s, sort_keys=False, allow_unicode=True)
    else:
        with open(settings_file, 'r') as s:
            settings = Dict(yaml.full_load(s))

    return settings

# Cell

DEVICE = get_device()
settings = read_settings()

DATA_STORE         = settings.STORES.DATA_STORE
LOG_STORE          = settings.STORES.LOG_STORE
MODEL_STORE        = settings.STORES.MODEL_STORE
EXPERIMENT_STORE   = settings.STORES.EXPERIMENT_STORE

PATH_AMP   = f'{DATA_STORE}/amp'
PATH_ACP  = f'{DATA_STORE}/acp'
PATH_DNA_BINDING  = f'{DATA_STORE}/dna_binding'
