# AUTOGENERATED! DO NOT EDIT! File to edit: 02_preprocessing_embedding.ipynb (unless otherwise specified).

__all__ = []

# Cell
import string

from .data import *
from sklearn.preprocessing import MultiLabelBinarizer, OneHotEncoder